language: python
sudo: true
python:
    - "2.7"
    - "3.6"
    - "3.8"

install:
  - "pip install python-coveralls"
  - "pip install coverage"
  - "pip install flake8"
  - "sudo python ./setup.py install"

before_script:
  - "flake8 setup.py mppsolar tests"

script:
  - "coverage run sudo ./setup.py test"

after_success:
  - "coverage report"
  - "coveralls"

notifications:
  email: false
