services:
  mosquitto:
    image: eclipse-mosquitto
    network_mode: host
    volumes:
      - ./docker/mosquitto/config:/mosquitto/config
      - ./docker/mosquitto/data:/mosquitto/data
      - ./docker/mosquitto/log:/mosquitto/log

  mppsolar:
    network_mode: host
    devices:
     - /dev/hidraw0:/dev/hidraw0
    volumes:
    #Bind over the configuration
      - type: bind
        source: ./docker/
        target: /etc/mpp-solar
    #Bind the code
      - type: bind
        source: .
        target: /mpp-solar
    build: .
    entrypoint:
      - mpp-solar
      - -C
      - /etc/mpp-solar/mpp-solar.conf #Available due to volume binding above
      - --daemon
    depends_on:
      - mosquitto


