services:
  mosquitto:
    image: eclipse-mosquitto
    network_mode: host
    volumes:
      - ./docker/mosquitto/config:/mosquitto/config
      - ./docker/mosquitto/data:/mosquitto/data
      - ./docker/mosquitto/log:/mosquitto/log

  mppsolar:
    network_mode: host
    devices:
     - /dev/hidraw0:/dev/hidraw0
    volumes:
    #Bind over the configuration
      - type: bind
        source: ./docker/dev/config/
        target: /config
    #Bind the code
#      - type: bind
#        source: ../..
#        target: /mpp-solar
    build:
      context: ./
      dockerfile: docker/dev/Dockerfile
    entrypoint:
      - powermon
      - -C
      - /config/powermon.yaml #Available due to volume binding above
      - --debug
#       - sleep
#       - infinity
    depends_on:
      - mosquitto

  mppsolar-api:
    network_mode: host
    build: 
      context: api
      dockerfile: Dockerfile.development
    entrypoint: 
      - node
      - index.js
    depends_on:
      - mppsolar


