# yaml config for powermon
device:
  name: 1012LV-MK
  id: 123456789
  model: 1012LV-MK
  manufacturer: MPP-Solar
  port:
    path: /dev/hidraw0
    type: usb
    protocol: PI30

commands:
- command: QPIRI #Must be in the protocol command list
  trigger:
    every: 100  # seconds
  outputs:
  - type: api_mqtt
    format: 
      type: simple
          
mqttbroker:
  name: localhost
  port: 1883
  username: null
  password: null

api:
  announce_topic: powermon/announce
  adhoc_topic: powermon/adhoc
  refresh_interval: 30

daemon:
  type: systemd
  keepalive: 100